import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import Post from '../components/Post'
import { PostType } from '../types'

const Home: NextPage = ({ data }: any) => {

  console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col gap-6 items-center justify-center'>
        {data.map((post: PostType) => (
          <Post post={post} key={post._id}/>
        ))}
      </div>
    </>
  )
}

export default Home

export async function getServerSideProps()  {
  const res = await fetch('http://localhost:3000/api/discover');

  const data = await res.json()

  return {
    props: { data }
  }
}
